name: Auto-approve & Auto-merge auto-* PRs

on:
  pull_request:
    branches: [ main ]                     # Target branch for the PR
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto_merge:
    if: startsWith(github.head_ref, 'auto-') && github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      # Built-in GitHub CLI on ubuntu-latest is recent enough; no upgrade needed
      - name: Verify GitHub CLI
        run: gh --version

      - name: Capture PR context
        id: ctx
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
          echo "AUTHOR=${{ github.event.pull_request.user.login }}" >> "$GITHUB_OUTPUT"
          echo "HEAD_REF=${{ github.head_ref }}" >> "$GITHUB_OUTPUT"
          echo "BASE_REF=${{ github.base_ref }}" >> "$GITHUB_OUTPUT"

      # Ensure approver identity differs from PR author
      - name: Guard identities (approver ≠ author)
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT }}
        run: |
          set -euo pipefail
          APPROVER=$(gh api user --jq .login)
          echo "PR author : ${{ steps.ctx.outputs.AUTHOR }}"
          echo "Approver  : $APPROVER"
          if [ "$APPROVER" = "${{ steps.ctx.outputs.AUTHOR }}" ]; then
            echo "::error::Approver and author are the same. Use a different account for BOT_PAT."
            exit 1
          fi

      - name: Approve PR
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT }}
        run: |
          set -euo pipefail
          gh pr review ${{ steps.ctx.outputs.PR_NUMBER }} --approve
          echo "✅ Approved PR #${{ steps.ctx.outputs.PR_NUMBER }}"

      - name: Enable Auto-merge (delete branch after merge)
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT }}
        run: |
          set -euo pipefail
          gh pr merge ${{ steps.ctx.outputs.PR_NUMBER }} --auto --merge --delete-branch
          echo "✅ Auto-merge enabled for PR #${{ steps.ctx.outputs.PR_NUMBER }}"

      - name: Done
        run: echo "Workflow finished successfully."
