name: Auto PR and Merge

on:
  push:
    branches:
      - "auto-*"

jobs:
  create_and_merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
        with:
          script: |
            const { repo, owner } = context.repo;
            const base = "main";
            const head = process.env.GITHUB_REF.replace("refs/heads/", "");
            const prs = await github.rest.pulls.list({ owner, repo, head: `${owner}:${head}`, base });
            if (prs.data.length === 0) {
              const pr = await github.rest.pulls.create({
                owner,
                repo,
                head,
                base,
                title: `Auto PR from ${head} to ${base}`,
                body: 'Automated PR',
              });
              core.setOutput('pr_number', pr.data.number);
            } else {
              core.setOutput('pr_number', prs.data[0].number);
            }

      - name: Approve PR
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
        with:
          github-token: ${{ secrets.BOT_PAT }}
          script: |
            const pr_number = core.getInput('pr_number');
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              event: 'APPROVE'
            });

      - name: Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
        run: |
          PR_NUMBER=$(echo ${{ steps.create_pr.outputs.pr_number }})
          gh pr merge $PR_NUMBER --merge --admin --repo $GITHUB_REPOSITORY
